"""add rental options

Revision ID: e7c763f62dea
Revises: ff7309cc5a92
Create Date: 2026-08-08 15:10:58.013779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c763f62dea'
down_revision: Union[str, Sequence[str], None] = 'ff7309cc5a92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_options_id'), 'rental_options', ['id'], unique=False)
    op.create_table('vehicle_rental_options',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('rental_option_id', sa.Integer(), nullable=False),
    sa.Column('is_included', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rental_option_id'], ['rental_options.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('vehicle_id', 'rental_option_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_rental_options')
    op.drop_index(op.f('ix_rental_options_id'), table_name='rental_options')
    op.drop_table('rental_options')
    # ### end Alembic commands ###
