"""add vehicle engine and mileage

Revision ID: ff7309cc5a92
Revises: e43934182847
Create Date: 2026-08-07 14:36:09.834157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff7309cc5a92'
down_revision: Union[str, Sequence[str], None] = 'e43934182847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_engines_id'), 'engines', ['id'], unique=False)
    op.create_table('model_engines',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('engine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['engine_id'], ['engines.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('model_id', 'engine_id'),
    sa.UniqueConstraint('model_id', 'engine_id', name='uq_model_engines_model_id_engine_id')
    )
    op.create_unique_constraint('uq_models_brand_id_name', 'models', ['brand_id', 'name'])
    op.add_column('vehicles', sa.Column('engine_id', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('mileage', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_vehicles_engine_id_engines', 'vehicles', 'engines', ['engine_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_vehicles_engine_id_engines', 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'mileage')
    op.drop_column('vehicles', 'engine_id')
    op.drop_constraint('uq_models_brand_id_name', 'models', type_='unique')
    op.drop_table('model_engines')
    op.drop_index(op.f('ix_engines_id'), table_name='engines')
    op.drop_table('engines')
    # ### end Alembic commands ###
